Metatags + fixes
Sebosun/monte-cinema pull request #19
Opened 2022-03-16 10:37 UTC by Sebosun

2022-03-17 13:39 UTC, szymonlankauf requested changes

2022-03-17 13:39 UTC, szymonlankauf commented on src/components/sections/Screenings.vue
> +    CalendarSVG,
And this code is repeated as well

2022-03-17 13:39 UTC, szymonlankauf commented on src/components/sections/Screenings.vue
> +      <div v-else-if="error.status" class="screenings__error">
As mentioned before `loading` and `error` are not elements, but would make good modifiers.
`screenings--error`, `screenings--loading`?

2022-03-17 13:39 UTC, szymonlankauf commented on src/components/sections/Screenings.vue
> +  &__buttons {
I assume `buttons` is class of some kind of button container?
If so please rename it to what it actually is: `__button-container` - small change but makes reading the styles a lot easier 😉

2022-03-17 13:39 UTC, szymonlankauf commented on src/components/sections/ScreeningsForOneMovie.vue
> +      return this.selectedDayScreenings.length == 0;
I know I am picky now but it's usually a good practice to check the type as well `=== 0`

2022-03-17 13:39 UTC, szymonlankauf commented on src/helpers/api/movies.js
> +  }
`If-else` walls are not pretty and often tricky to refactor. Maybe something like this can inspire you to find a better solution:
```
export const handleGetSeances = async ({ date, id }) => {
  fetchSeances(getQuery({ date, id }))
};

const getQuery = ({ date, id }) => {
  const movieQuery = id ? `movie_id=${id}` : ''
  const dateQuery = date ? `date=${formatDateForFetch(date)}` : ''
  return date && id ? [movieQuery, dateQuery].join('&') : [movieQuery, dateQuery].join('')
}

const fetchSeances = async (query = '') => {
  return await defaultClient.get(`/seances?${query}`);
}
```

2022-03-17 15:02 UTC, Sebosun commented on src/components/chunks/UserInformationForm.vue
> +  },
Ussed, Error is bound in RegisterPage.vue

2022-03-17 15:06 UTC, Sebosun commented on src/components/chunks/UserInformationForm.vue
> +import ErrorMessage from "../UI/ErrorMessage.vue";
True, I keep forgetting that my automatic imports are relative and not absolute :P

2022-03-17 16:02 UTC, Sebosun commented on src/components/chunks/EmailPasswordFormValidated.vue
>    &__forgot a {
The `a` styling is being used. The "forgot" section has a router-link which I stylize with that part

2022-03-17 16:03 UTC, Sebosun commented on src/components/sections/Screenings.vue
> +    },
Seems like it's a git issue, my local version of this branch doesn't have this issue. This code wasn't even being updated in this branch :P

2022-03-17 20:35 UTC, rossinek commented on src/helpers/api/movies.js
> +  }
There is even simpler way if you do use `axios`. See how you can use `params` attribute here: https://axios-http.com/docs/example

[from docs](https://axios-http.com/docs/req_config):
> `params` are the URL parameters to be sent with the request
Must be a plain object or a `URLSearchParams` object
NOTE: params that are `null` or `undefined` are not rendered in the URL.

2022-03-18 07:52 UTC, Sebosun commented on src/components/sections/Screenings.vue
> +      const UNIX_ONE_DAY = 24 * 3600 * 1000; //one day
Will be done. As for the 3rd point, I don't think it's all that necessary since I don't think I'll be reusing this particular logic anywhere else, exporting it to a separate file would seem confusing. But I'll definitely keep this in mind when I'll be working with dates further on in this project :)

2022-03-18 08:48 UTC, Sebosun commented on src/components/sections/Screenings.vue
> +      const UNIX_ONE_DAY = 24 * 3600 * 1000; //one day
nvm i've done it anyway 🤦🏻

2022-03-18 10:50 UTC, szymonlankauf requested changes

2022-03-18 10:50 UTC, szymonlankauf commented on src/components/chunks/EmailPasswordFormValidated.vue
>      },
I was thinking about these 3 getters as well 🤔  they basically do the same thing just checking for different conditions. Also they return class names, but the name of these computed don't suggest that. Maybe we could refactor this a bit to make it more readable?
What if we separate validation logic from returning class name logic with something like this:

```
computed: {
  passwordValidation() {
    return {
      length: this.isPasswordTouched ? this.password.length > 8 : undefined,
      digits: this.isPasswordTouched ? !!this.password.match(/\d/) : undefined,
      letters: this.isPasswordTouched ? !!this.password.match(/[a-zA-Z]/) : undefined,
    }
  },
},
methods: {
  getValidationClass(validationType) {
    const validator = this.passwordValidation[validationType]
    if (typeof validator === "undefined") return ""
    return validator ? "validated-form__info" : "validated-form__info--error";
  },
}
```
then in the template you could use it like this:
```
<p :class="getValidationClass('length')">At least 8 characters</p>
```

2022-03-22 09:43 UTC, merged